run:
  timeout: 5m
  issues-exit-code: 1
output:
  formats: 
  - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
linters-settings:
  misspell:
    locale: US
linters:
  enable:
    - errcheck
    - goconst
    - godot
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unparam
    - unused
    - exportloopref
    - promlinter