version: "2"
run:
  timeout: 5m
output:
  formats:
    text:
      path: stdout
      color: true
      print-issued-lines: true
      print-linter-name: true
linters:
  settings:
    misspell:
      locale: US
  enable-all: true