{{- if .Values.loggen }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggen
  namespace: {{ .Values.namespace }}
  labels:
    app: loggen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loggen
  template:
    metadata:
      labels:
        app: loggen
        purpose: logging
      annotations: {{ (default dict .Values.loggen.pod.annotations) | toYaml | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.priorityClassName }}
      affinity: {{ (default dict .Values.loggen.pod.affinity) | toYaml | nindent 8 }}
      serviceAccountName: default
      containers:
        - name: loggen
          image: {{ required "this value is required" .Values.loggen.container.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          args:
          - --gen.size=100
          - --serverAddr=:{{ .Values.loggen.options.metricPort }}
          - --inspector.lobsterQueryEndpoint={{ .Values.loggen.options.lobsterQueryEndpoint }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.loggen.options.metricPort }}
              protocol: TCP
          resources: {{ (default dict .Values.loggen.container.resources) | toYaml | nindent 12 }}
          env:
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONTAINER
            value: loggen
      tolerations: {{ (default list .Values.loggen.pod.tolerations) | toYaml | nindent 8 }}
{{- end }}